spring:
  application:
    name: referral
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.0.80:3306/referral?characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false&useSSL=false&allowPublicKeyRetrieval=TRUE&allowMultiQueries=true
    username: root
    password: WOW@wow123
    hikari:
      minimum-idle: 10
      maximum-pool-size: 100
      idle-timeout: 30000
      pool-name: CPPool
      max-lifetime: 1800000
      connection-timeout: 31000
      connection-test-query: SELECT 1
  redis:
    redisson:
      config: |
        singleServerConfig:
          database: 0
          address: redis://192.168.0.80:6379
          password: J2i1KpI1d3
          idleConnectionTimeout: 10000
          connectTimeout: 10000
          timeout: 10000
          retryAttempts: 3
          retryInterval: 1500
          connectionMinimumIdleSize: 24
          connectionPoolSize: 64
          dnsMonitoringInterval: 5000
          pingConnectionInterval: 30000
  rabbitmq:
    addresses: amqp://192.168.0.80:5672
    username: guest
    password: guest
    template:
      retry:
        enabled: true
        max-interval: 3000ms
        max-attempts: 5
        multiplier: 1.2
        initial-interval: 1000ms

app:
  task-config:
    enable: ${ENABLE_TASK:true}
  authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MTI0Nzc3MDcsInN1YiI6InN5c3RlbTAifQ.KpVM1JsA2a_G-md6-3Sxjb4p8ipoX-M6VoepFZCR3kA
  uc:
    rpc:
      get-user-url: http://192.168.0.80:7878/xstock_api/s/u/getById/
  chainbridge:
    rpc:
      withdraw-url: http://192.168.0.161:3002/dex/token/transfer
      token: 3L2zvOJTWzJlNeiB+4eY1LIifaPDdrOL/5sUYkHdMs8J7BuTptj7RaMI4EAHCqXR
      callback-url: http://192.168.0.161:7890/referral/c/referral/callback
      referral-write-url: http://192.168.0.80:7021/s/chainbridge/wrc
      referral-read-url: http://192.168.0.80:7021/s/chainbridge/rrc