spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.0.80:3306/statistics?characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false&useSSL=false&allowPublicKeyRetrieval=TRUE&allowMultiQueries=true
    username: dex
    password: DexA1@3aa
    hikari:
      minimum-idle: 10
      maximum-pool-size: 100
      idle-timeout: 30000
      pool-name: CPPool
      max-lifetime: 1800000
      connection-timeout: 31000
      connection-test-query: SELECT 1
  redis:
    redisson:
      config: |
        singleServerConfig:
          database: 0
          address: redis://192.168.0.80:6379
          password: J2i1KpI1d3
          idleConnectionTimeout: 10000
          connectTimeout: 10000
          timeout: 10000
          retryAttempts: 3
          retryInterval: 1500
          connectionMinimumIdleSize: 24
          connectionPoolSize: 64
          dnsMonitoringInterval: 5000
          pingConnectionInterval: 30000
  rabbitmq:
    addresses: amqp://192.168.0.80:5672
    username: guest
    password: guest
    template:
      retry:
        enabled: true
        max-interval: 3000ms
        max-attempts: 5
        multiplier: 1.2
        initial-interval: 1000ms

app:
  task-config:
    enable: ${ENABLE_TASK:true}
  uc:
    sys_conf_url: http://192.168.0.80:7878/xstock_api/a/c/getConfig
    user_remain_url: http://192.168.0.80:7878/xstock_api/s/u/checkNewAddress
    user_reg_count_url: http://192.168.0.80:7878/xstock_api/s/u/txAddress
    data_fee_url: http://192.168.0.80:14321/analysis/b/statistics/dateFee
    token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MTExODg5NDksInN1YiI6InN5c3RlbV9haSJ9.LsmxgkBwacEwsEp2PlqRhtfYn52VWwRc2RJ8fYLoJxo